version: "3.7"
services:
  django:
    # コンテナ名
    container_name: django
    # ビルドするdockerファイルが格納されたディレクトリ
    build: ./django
    # 正常起動後に実行するコマンド
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      # マウントするディレクトリ
      - ./django:/usr/src/app/
    ports:
      # ホスト側のポート：コンテナ側のポート
      - 8000:8000
    env_file:
      # 環境変数に設定するファイル
      -  ./django/.env
    depends_on:
      # 接続するサービス
      - postgres
    networks:
      - front
      - back

  postgres:
    container_name: postgres
    build: ./postgres
    volumes:
      # DBのデータはボリュームを作成して保存
      # ディレクトリとマウントとって実データをホストOSに直接残しても良い
      # /var/lib/postgresql/dataにDBのデータが格納されている
      - db_postgis_data:/var/lib/postgresql/data
      # down -vなどでボリュームがない時などを含めた初回起動時に実行されるファイルを指定
      - ./postgres/sql:/docker-entrypoint-initdb.d
    env_file: ./postgres/.env_db
    ports:
      # ホスト側のポートはローカルのpsqlとバッティングするので5432以外にする
      - 5433:5432
    networks:
      - back

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./django/static:/usr/src/app/static
    ports:
      - 9000:80
    depends_on:
      - django
    networks:
      - front

  pgadmin4:
    image:  dpage/pgadmin4:latest
    volumes:
      - pgadmin4:/var/lib/pgadmin
    env_file:
      - ./.env.development
    ports:
      - 5555:80
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - back

volumes:
  db_postgis_data:
  pgadmin4:
  static_volume:
  media_volume:

networks:
  front:
    external: false
  back:
    external: false
